import { type WorkflowCreate } from "@dynatrace-sdk/client-automation";
import { WORKFLOW_VERSION } from "../../constants/constants";

const appId = "my.dql.consumption.assistant"; // deployed app id

// Get rate card action
export const actionGetRateCard = appId + ":get_rate_card";

// Consumption action
export const actionGetUsersConsumption = appId + ":calculate_users_consumption";

// User group action
export const actionAddUsersToGroup =
  appId + ":adjust_user_consumption_cooldown";

export const workflowTitle = `DQL Consumption (${WORKFLOW_VERSION})`;

export const workflow: WorkflowCreate = {
  title: workflowTitle,
  tasks: {
    // Get Rate Card
    get_rate_card: {
      name: "get_rate_card",
      action: actionGetRateCard,
      position: {
        x: 0,
        y: 1,
      },
      description: "Gathers Rate card data via Dynatrace accounts API",
      conditions: {
        custom: "",
        states: {},
      },
      predecessors: [],
    },

    // Logs Consumption
    calculate_users_log_consumption: {
      name: "calculate_users_log_consumption",
      action: actionGetUsersConsumption,
      position: {
        x: 0,
        y: 2,
      },
      description: "Get Users Log Consumption",
      input: {
        eventType: "logs",
        rateCard: '{{result("get_rate_card")}}',
      },
      conditions: {
        custom: "",
        states: { get_rate_card: "OK" },
      },
      predecessors: ["get_rate_card"],
    },
    adjust_user_log_consumption_cooldown: {
      name: "adjust_user_log_consumption_cooldown",
      input: {
        eventType: "logs",
        users: '{{result("calculate_users_log_consumption")}}',
      },
      action: actionAddUsersToGroup,
      position: {
        x: 0,
        y: 3,
      },
      conditions: {
        custom: '{{ result("calculate_users_log_consumption") | length > 0 }}',
        states: {
          calculate_users_log_consumption: "OK",
        },
      },
      description: "Add High Logs Consumption Users to Group",
      predecessors: ["calculate_users_log_consumption"],
    },
    logs_cooldown_email: {
      name: "logs_cooldown_email",
      action: "dynatrace.email:send-email",
      input: {
        subject: "Logs DQL consumption report",
        taskId: "{{ task().id }}",
        content: `The following users have exceeded the configured consumption limit for querying logs: \n\n{% for record in result("adjust_user_log_consumption_cooldown") %}\n* {{ record.user_email }}{% if record.cost is defined %} : {{ result('get_rate_card')[0].currencyCode | default('') }} {{ record.cost }} {{ result('get_rate_card')[0].currencyCode  | default('') }} (>= {{ record.set_by.threshold }} for {{ record.set_by.group_name if record.set_by.group_name else "Global" }}){% endif %}{% if record.change is defined %} - cooldown {{ record.change }}{% endif %}  \n{% endfor %}\n\n{% set with_change = result("adjust_user_log_consumption_cooldown") | selectattr("change", "defined") | list %}\n\n{% if with_change | length == 0 %}\nNo cooldown group configured for logs querying. Cooldown groups can be set up in Settings -> DQL Consumption -> Logs Cooldown group\n{% endif %}\n\nThis report was generated by DQL Consumption Assistant Workflow.`,
        executionId: "{{ execution().id }}",
        environmentUrl: "{{ environment().url }}",
      },
      conditions: {
        custom:
          '{{ result("adjust_user_log_consumption_cooldown") | length > 0 }}',
        states: {
          adjust_user_log_consumption_cooldown: "OK",
        },
      },
      position: {
        x: 0,
        y: 4,
      },
      description: "Send email",
      predecessors: ["adjust_user_log_consumption_cooldown"],
    },

    // Bizevents consumption
    calculate_users_event_consumption: {
      name: "calculate_users_event_consumption",
      action: actionGetUsersConsumption,
      position: {
        x: -1,
        y: 2,
      },
      description: "Get Users Event Consumption",
      input: {
        eventType: "events",
        rateCard: '{{result("get_rate_card")}}',
      },
      conditions: {
        custom: "",
        states: { get_rate_card: "OK" },
      },
      predecessors: ["get_rate_card"],
    },
    adjust_user_event_consumption_cooldown: {
      name: "adjust_user_event_consumption_cooldown",
      input: {
        eventType: "events",
        users: '{{result("calculate_users_event_consumption")}}',
      },
      action: actionAddUsersToGroup,
      position: {
        x: -1,
        y: 3,
      },
      conditions: {
        custom:
          '{{ result("calculate_users_event_consumption") | length > 0 }}',
        states: {
          calculate_users_event_consumption: "OK",
        },
      },
      description: "Add High Events Consumption Users to Group",
      predecessors: ["calculate_users_event_consumption"],
    },
    events_cooldown_email: {
      name: "events_cooldown_email",
      action: "dynatrace.email:send-email",
      input: {
        subject: "Events DQL consumption report",
        taskId: "{{ task().id }}",
        content: `The following users have exceeded the configured consumption limit for querying BizEvents: \n\n{% for record in result("adjust_user_event_consumption_cooldown") %}\n* {{ record.user_email }}{% if record.cost is defined %} : {{ result('get_rate_card')[0].currencyCode  | default('') }} {{ record.cost }} (>= {{ result('get_rate_card')[0].currencyCode  | default('') }}{{ record.set_by.threshold }} for {{ record.set_by.group_name if record.set_by.group_name else "Global" }}){% endif %}{% if record.change is defined and record.change %} - cooldown {{ record.change }}{% endif %}  \n{% endfor %}\n\n{% set with_change = result("adjust_user_log_consumption_cooldown") | selectattr("change", "defined") | list %}\n\n{% if with_change | length == 0 %}\nNo cooldown group configured for events querying. Cooldown groups can be set up in Settings -> DQL Consumption -> Events Cooldown group\n{% endif %}\n\nThis report was generated by DQL Consumption Assistant Workflow.`,
        executionId: "{{ execution().id }}",
        environmentUrl: "{{ environment().url }}",
      },
      conditions: {
        custom:
          '{{ result("adjust_user_event_consumption_cooldown") | length > 0 }}',
        states: {
          adjust_user_event_consumption_cooldown: "OK",
        },
      },
      position: {
        x: -1,
        y: 4,
      },
      description: "Send email",
      predecessors: ["adjust_user_event_consumption_cooldown"],
    },

    //Traces consumption
    calculate_users_traces_consumption: {
      name: "calculate_users_traces_consumption",
      action: actionGetUsersConsumption,
      position: {
        x: 1,
        y: 2,
      },
      description: "Get users traces consumption",
      input: {
        eventType: "traces",
        rateCard: '{{result("get_rate_card")}}',
      },
      conditions: {
        custom: "",
        states: { get_rate_card: "OK" },
      },
      predecessors: ["get_rate_card"],
    },
    adjust_user_traces_consumption_cooldown: {
      name: "adjust_user_traces_consumption_cooldown",
      input: {
        eventType: "traces",
        users: '{{result("calculate_users_traces_consumption")}}',
      },
      action: actionAddUsersToGroup,
      position: {
        x: 1,
        y: 3,
      },
      conditions: {
        custom:
          '{{ result("calculate_users_traces_consumption") | length > 0 }}',
        states: {
          calculate_users_traces_consumption: "OK",
        },
      },
      description: "Add High Traces Consumption Users to Group",
      predecessors: ["calculate_users_traces_consumption"],
    },
    traces_cooldown_email: {
      name: "traces_cooldown_email",
      action: "dynatrace.email:send-email",
      input: {
        subject: "Traces DQL consumption report",
        taskId: "{{ task().id }}",
        content: `The following users have exceeded the configured consumption limit for querying Traces: \n\n{% for record in result("adjust_user_traces_consumption_cooldown") %}\n* {{ record.user_email }}{% if record.cost is defined %} : {{ result('get_rate_card')[0].currencyCode  | default('') }}{{ record.cost }} (>= {{ result('get_rate_card')[0].currencyCode  | default('') }}{{ record.set_by.threshold }} for {{ record.set_by.group_name if record.set_by.group_name else "Global" }}){% endif %}{% if record.change is defined and record.change %} - cooldown {{ record.change }}{% endif %}  \n{% endfor %}\n\n{% set with_change = result("adjust_user_log_consumption_cooldown") | selectattr("change", "defined") | list %}\n\n{% if with_change | length == 0 %}\nNo cooldown group configured for events querying. Cooldown groups can be set up in Settings -> DQL Consumption -> Traces Cooldown group\n{% endif %}\n\nThis report was generated by DQL Consumption Assistant Workflow.`,
        executionId: "{{ execution().id }}",
        environmentUrl: "{{ environment().url }}",
      },
      position: {
        x: 1,
        y: 4,
      },
      conditions: {
        custom:
          '{{ result("adjust_user_traces_consumption_cooldown") | length > 0 }}',
        states: {
          adjust_user_traces_consumption_cooldown: "OK",
        },
      },
      description: "Send email",
      predecessors: ["adjust_user_traces_consumption_cooldown"],
    },
  },
  description: "",
  ownerType: "USER",
  isPrivate: true,
  type: "STANDARD",
  trigger: {
    schedule: {
      trigger: {
        time: "10:00",
        type: "time",
      },
      timezone: "EST",
    },
  },
  hourlyExecutionLimit: 1000,
  schemaVersion: 3,
};
